[tool.black]
line-length = 79
target-version = ['py312']

[tool.isort]
profile = "black"
py_version = 312
line_length = 79
multi_line_output = 3
skip_gitignore = true
atomic = true
use_parentheses = true
combine_as_imports = true
virtual_env = ".venv"

[tool.pylint.main]
py-version = [3, 12]

[tool.pylint."MESSAGES CONTROL"]
disable = ["C0114", "C0103"]

[tool.pyright]
pythonVersion = "3.12"
